kind: pipeline
type: docker
name: DB_PIPELINE


steps:
  - name: deploy-container-pgsql
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: postgres:latest
      CONTAINERNAME: bigbrotherdb
      COMMAND: create
      OVERWRITE: false
      PRIVATE: true
      CODEFIRST_CLIENTDRONE_ENV_POSTGRES_ROOT_PASSWORD:
        from_secret: db_root_password
      CODEFIRST_CLIENTDRONE_ENV_POSTGRES_DATABASE:
        from_secret: db_database
      CODEFIRST_CLIENTDRONE_ENV_POSTGRES_USER:
        from_secret: db_user
      CODEFIRST_CLIENTDRONE_ENV_POSTGRES_PASSWORD:
        from_secret: db_password

  - name: create-bigbrother-database
    image: python:latest
    commands:
      - echo $POSTGRES_DATABASE
      - cd database/
      - pip install psycopg2
      - python3 db-creation.py
    environment:
     POSTGRES_ROOT_PASSWORD:
       from_secret: db_root_password
     POSTGRES_DATABASE:
       from_secret: db_database
     POSTGRES_USER:
       from_secret: db_user
     POSTGRES_PASSWORD:
       from_secret: db_password
    secrets: [ db_root_password , db_database , db_user , db_password ]
    depends_on: [ deploy-container-pgsql ]
